version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - downloads:/app/downloads
    environment:
      - PYTHONPATH=/app

volumes:
  downloads:
    driver: local